
services:
  python:
    build: 
      context: .
    container_name: backend-api
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: tail -f /dev/null #mantenedor el contenedor en ejecución
    ports:
      - "80:80"
    environment:
      - PYTHONUNBUFFERED=1
    