
services:
  python:
    build: 
      context: .
    container_name: python-dev
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: tail -f /dev/null #mantenedor el contenedor en ejecución
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - custom_network

